Django/Spring2018Pythonzoo-master/pythonzoo/pythonzoo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('zoo/', include('zoo.urls')),
	path('', RedirectView.as_view(url='/zoo/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Django/Spring2018Pythonzoo-master/pythonzoo/zoo/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ZooListView.as_view(), name='zooList'),
    path('<int:pk>', views.ZooDetailView.as_view(), name='zooDetail'),
    path('exhibit/<int:pk>', views.ExhibitDetailView.as_view(), name='exhibitDetail'),
    path('animal/<int:pk>', views.AnimalDetailView.as_view(), name='animalDetail'),
    path('aboutus', views.aboutus, name='aboutus'),

]

Django/Spring2018Pythonzoo-master/pythonzoo/zoo/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Zoo(models.Model):
	name = models.CharField(max_length=200, help_text="Enter Zoo Name")
	logoFileName = models.CharField(max_length=200, help_text="Enter logo file name", null=True)

	def __str__ (self):
		return self.name

	def get_absolute_url(self):
		return reverse('zooDetail', args=[str(self.id)])

class Exhibit(models.Model):
	name = models.CharField(max_length=200, help_text="Enter Exhbit Name")
	zoo = models.ForeignKey('Zoo', on_delete=models.SET_NULL, null=True)

	def __str__ (self):
		return self.name

	def get_absolute_url(self):
		return reverse('exhibitDetail', args=[str(self.id)])

	def getZooName(self):
		return self.zoo.name

class Animal(models.Model):
	name = models.CharField(max_length=200, help_text="Enter Animal Name")
	imageFileName = models.CharField(max_length=200, help_text="Enter logo file name", null=True)
	exhibit = models.ForeignKey('Exhibit', on_delete=models.SET_NULL, null=True)
	soundFileName = models.CharField(max_length=200, help_text="Enter sound file name", null=True, blank=True)
	habitatDescription = models.TextField(max_length=1000, help_text='Enter a description of the habitat')
	dietDescription = models.TextField(max_length=1000, help_text='Enter a description of the diet')

	def __str__ (self):
		return self.name

	def get_absolute_url(self):
		return reverse('animalDetail', args=[str(self.id)])

class ExhibitNeighbor(models.Model):
	fromExhibit = models.ForeignKey('Exhibit', on_delete=models.SET_NULL, null=True, related_name='fromExhibit')
	toExhibit = models.ForeignKey('Exhibit', on_delete=models.SET_NULL, null=True, related_name='toExhibit')
	CARDINAL = (
		('n', 'North'),
		('s', 'South'),
		('w', 'West'),
		('e', 'East'),
		('nw', 'Northwest'),
		('ne', 'Northeast'),
		('sw', 'Southwest'),
		('se', 'Southeast')
	)
	direction = models.CharField(max_length=2, choices=CARDINAL, help_text="Enter Direction", null=True, blank=True)

Django/Spring2018Pythonzoo-master/pythonzoo/zoo/views.py
from django.shortcuts import render
from django.views import generic

from .models import Zoo, Exhibit, Animal

# Create your views here.

def aboutus(request):
	return render(
		request,
		"zoo/aboutus.html",
		context = {  },
	)

class ZooListView(generic.ListView):
	model = Zoo

class ZooDetailView(generic.DetailView):
    model = Zoo

class ExhibitDetailView(generic.DetailView):
    model = Exhibit

class AnimalDetailView(generic.DetailView):
    model = Animal

Django/Spring2018Pythonzoo-master/pythonzoo/zoo/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Welcome to my Zoo</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <h1>This is the navigation bar</h1>
  <p>Contact Us</p>
  <hr>

	{% block content %}{% endblock %}

</body>

</html>

Django/Spring2018Pythonzoo-master/pythonzoo/zoo/templates/index.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Hello {{ temporaryData }} </h1>

{% endblock %}

Django/Spring2018Pythonzoo-master/pythonzoo/zoo/templates/zoo/aboutus.html
{% extends "base_generic.html" %}

{% block content %}

<h1>About Us</h1>

{% endblock %}

Django/Spring2018Pythonzoo-master/pythonzoo/zoo/templates/zoo/animal_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Animal Detail for {{ animal.id }} - {{ animal.name }} in
  {{ animal.exhibit.name }} in {{ animal.exhibit.zoo.name }}</h1>

<h1>Image</h1>
{% load static %}
<img src="{% static animal.imageFileName %}">

{% endblock %}

Django/Spring2018Pythonzoo-master/pythonzoo/zoo/templates/zoo/exhibit_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Exhbit Detail for {{ exhibit.id }} - {{ exhibit.name }} in {{ exhibit.zoo.name }}</h1>

<h1>Neighbors</h1>

{% for neighbor in exhibit.fromExhibit.all %}
  <p>{{ neighbor.direction }} to {{ neighbor.toExhibit.name }}
{% endfor %}


<h1>Animals</h1>

{% for animal in exhibit.animal_set.all %}
  <p>{{ animal.name }}</p>
{% endfor %}


{% endblock %}

Django/Spring2018Pythonzoo-master/pythonzoo/zoo/templates/zoo/zoo_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Zoo Detail for {{ zoo.id }} - {{ zoo.name }}</h1>

{% endblock %}

Django/Spring2018Pythonzoo-master/pythonzoo/zoo/templates/zoo/zoo_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Zoo List</h1>

{% for zoo in zoo_list %}
  <p>{{ zoo.name }}</p>
{% endfor %}

{% endblock %}